### ISSUE TITLE
Surprisingly Much Worse Results on Inception-V3

### ISSUE THREAD

**Issue by ZhengyuZhao** [smartcameras/ColorFool#2]
Hi! Nice to read such interesting work!

I have tested the code on 1000 ImageNet images with the default three networks (AlexNet, ResNet15, and ResNet50), and got similar results as reported in your paper. 
However,  when I tried attacking an Inception-v3 model, the success rate dropped to only ~65%. I repeated with two image resolutions: 224x224 and 299x299, and max trials =1000 and 1500, the results remain almost the same.
Question: Have you ever tried other networks? Could you please help me figure out what may be happening here?

Thanks~!

**Comment by AliShahin** [comment]
> Hi! Nice to read such interesting work!
> 
> I have tested the code on 1000 ImageNet images with the default three networks (AlexNet, ResNet15, and ResNet50), and got similar results as reported in your paper.
> However, when I tried attacking an Inception-v3 model, the success rate dropped to only ~65%. I repeated with two image resolutions: 224x224 and 299x299, and max trials =1000 and 1500, the results remain almost the same.
> Question: Have you ever tried other networks? Could you please help me figure out what may be happening here?
> 
> Thanks~!

Dear Zhengyu,

Thanks for your interest in our work and reproducing our reported results. 

For this work we did not evaluate ColorFool on other classifiers apart from ResNet50, ResNet18 and AlexNet. 
I would suggest you to look at the log (class, confidence and perturbation per trial) of those ~35% images to see if there is any bug in your code or ColorFool is not able to fool that particular classifier. 
Also double check the integration of Inception-V3 please, e.g. pre-processing (mean and std) images during feeding to the model and saving, and check the consistency of measuring the accuracy during generating adversarial images and testing adversarial images.

Warm regards,
Ali
