### ISSUE TITLE
About Run Time

### ISSUE THREAD

**Issue by YogaLYJ** [smartcameras/ColorFool#3]
Hi, it is an interesting work. I test ColorFool on one GPU, attacking ResNet50 with 1000 images randomly chosen from ImageNet. I need nearly 20 hours to finish the attack (attacking 1000 images). Is this normal? Thanks!

**Comment by AliShahin** [comment]
Hello,
Thanks for your interest in our work!

Yes, it is normal. For each image, ColorFool performs up to 1000 trials. Running time of each trial includes perturbing the colour of objects in the Lab colour space and one forward-pass of your ResNet50 model.

**Comment by YogaLYJ** [comment]
> Hello,
> Thanks for your interest in our work!
> 
> Yes, it is normal. For each image, ColorFool performs up to 1000 trials. Running time of each trial includes perturbing the colour of objects in the Lab colour space and one forward-pass of your ResNet50 model.

Thanks！
